version: '3'
services:
  config-server:
    container_name: config-server
    build: config-server
    ports:
      - "8888:8888"
  eureka-server:
    container_name: eureka-server
    build: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
  zipkin-server:
    container_name: zipkin-server
    build: zipkin-server
    ports:
      - "9411:9411"
  db:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=mvarchenko
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=catalog
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  catalog-service:
    container_name: catalog-service
    build: catalog-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/catalog
      - SPRING_DATASOURCE_USER=mvarchenko
      - SPRING_DATASOURCE_PASSWORD=ubuntu
    depends_on:
      - config-server
      - db

  inventory-service:
    container_name: inventory-service
    build: inventory-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/catalog
      - SPRING_DATASOURCE_USER=mvarchenko
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - db
      - config-server

  product-service:
    container_name: product-service
    build: product-service
    ports:
      - "8083:8083"
    depends_on:
      - config-server


